"""empty message

Revision ID: a5777aa55134
Revises: b15b4bf456ab
Create Date: 2020-11-02 15:08:49.278701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5777aa55134'
down_revision = 'b15b4bf456ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('the_user', sa.Column('password', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('the_user', 'password')
    # ### end Alembic commands ###
