"""empty message

Revision ID: a6d11c62779f
Revises: e9e9a0df5437
Create Date: 2020-11-03 00:17:26.473641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6d11c62779f'
down_revision = 'e9e9a0df5437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotel', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotel', 'price')
    # ### end Alembic commands ###
