"""empty message

Revision ID: c616ce0a1704
Revises: 0b00d294218b
Create Date: 2020-11-02 18:14:02.134871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c616ce0a1704'
down_revision = '0b00d294218b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_password_hash', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', '_password_hash')
    # ### end Alembic commands ###
