"""empty message

Revision ID: f3c53cb4d458
Revises: c616ce0a1704
Create Date: 2020-11-02 19:30:33.234493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3c53cb4d458'
down_revision = 'c616ce0a1704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image1', sa.String(length=256), nullable=True),
    sa.Column('image2', sa.String(length=256), nullable=True),
    sa.Column('image3', sa.String(length=256), nullable=True),
    sa.Column('image4', sa.String(length=256), nullable=True),
    sa.Column('image5', sa.String(length=256), nullable=True),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
